{
  "smartphones": [
    {
      "name": "6",
      "brand": "Nokia",
      "imagelink": "images\\/TheNewNokia6_hardware-phone.jpg?fm=png",
      "price": 279,
      "design": 4,
      "display": 5.5,
      "length": 149,
      "width": 76,
      "processor": 3,
      "updates": 5,
      "camera": 3,
      "battery": 3,
      "storage": 32,
      "memory": 3,
      "sdslot": 1,
      "simcards": 2,
      "headphonejack": 1,
      "totalscore": 0,
      "asin_de": "B07B6C32JX",
      "price_de": 0,
      "amazon_de": ""
    },
    {
      "name": "7 plus",
      "brand": "Nokia",
      "imagelink": "images\\/Nokia7plus_ROW_hardware-phone.jpg?fm=png",
      "price": 399,
      "design": 4,
      "display": 6,
      "length": 158,
      "width": 76,
      "processor": 4,
      "updates": 5,
      "camera": 4,
      "battery": 5,
      "storage": 64,
      "memory": 4,
      "sdslot": 1,
      "simcards": 2,
      "headphonejack": 1,
      "totalscore": 0,
      "asin_de": "B07B6DMZN6",
      "price_de": 0,
      "amazon_de": ""
    },
    {
      "name": "8 Sirocco",
      "brand": "Nokia",
      "imagelink": "images\\/Nokia8Sirocco_ROW__power-phone.jpg?fm=png",
      "price": 749,
      "design": 5,
      "display": 5.5,
      "length": 141,
      "width": 73,
      "processor": 5,
      "updates": 5,
      "camera": 4,
      "battery": 4,
      "storage": 128,
      "memory": 6,
      "sdslot": 1,
      "simcards": 1,
      "headphonejack": 0,
      "totalscore": 0,
      "asin_de": "B07B69SLMB",
      "price_de": 0,
      "amazon_de": ""
    },
    {
      "name": "Mi A1",
      "brand": "Xiamoi",
      "imagelink": "images\\/y74WpwR.jpg",
      "price": 185,
      "design": 4,
      "display": 5.5,
      "length": 155,
      "width": 76,
      "processor": 3,
      "updates": 5,
      "camera": 3,
      "battery": 3,
      "storage": 64,
      "memory": 4,
      "sdslot": 1,
      "simcards": 2,
      "headphonejack": 1,
      "totalscore": 0,
      "asin_de": "B076493W9X",
      "price_de": 0,
      "amazon_de": ""
    },
    {
      "name": "Mi MIX 2",
      "brand": "Xiamoi",
      "imagelink": "images\\/7EIAsGt.jpg",
      "price": 377,
      "design": 5,
      "display": 6,
      "length": 152,
      "width": 76,
      "processor": 5,
      "updates": 2,
      "camera": 4,
      "battery": 4,
      "storage": 64,
      "memory": 6,
      "sdslot": 0,
      "simcards": 2,
      "headphonejack": 0,
      "totalscore": 0,
      "asin_de": "B0784RQR88",
      "price_de": 0,
      "amazon_de": ""
    },
    {
      "name": "U11 life",
      "brand": "HTC",
      "imagelink": "images\\/61iBTjkp3yL._SY741_.jpg",
      "price": 229,
      "design": 4,
      "display": 5.2,
      "length": 149,
      "width": 73,
      "processor": 3,
      "updates": 5,
      "camera": 3,
      "battery": 3,
      "storage": 32,
      "memory": 3,
      "sdslot": 2,
      "simcards": 2,
      "headphonejack": 0,
      "totalscore": 0,
      "asin_de": "B076HSNZ8H",
      "price_de": 0,
      "amazon_de": ""
    },
    {
      "name": "U11 \\+",
      "brand": "HTC",
      "imagelink": "images\\/51XltEAiihL._SY879_.jpg",
      "price": 641,
      "design": 5,
      "display": 6,
      "length": 159,
      "width": 75,
      "processor": 5,
      "updates": 4,
      "camera": 4,
      "battery": 5,
      "storage": 128,
      "memory": 6,
      "sdslot": 1,
      "simcards": 2,
      "headphonejack": 0,
      "totalscore": 0,
      "asin_de": "B077PMJM3M",
      "price_de": 0,
      "amazon_de": ""
    },
    {
      "name": "Pixel 2",
      "brand": "Google",
      "imagelink": "images\\/81Ea5V2MehL._SY879_.jpg",
      "price": 669,
      "design": 4,
      "display": 5,
      "length": 146,
      "width": 70,
      "processor": 5,
      "updates": 5,
      "camera": 5,
      "battery": 4,
      "storage": 64,
      "memory": 4,
      "sdslot": 0,
      "simcards": 1,
      "headphonejack": 0,
      "totalscore": 0,
      "asin_de": "B076L5FQ23",
      "price_de": 0,
      "amazon_de": ""
    },
    {
      "name": "Pixel 2 XL",
      "brand": "Google",
      "imagelink": "images\\/pixel2xl.jpg",
      "price": 731,
      "design": 4,
      "display": 6,
      "length": 158,
      "width": 77,
      "processor": 5,
      "updates": 5,
      "camera": 5,
      "battery": 4,
      "storage": 64,
      "memory": 4,
      "sdslot": 0,
      "simcards": 1,
      "headphonejack": 0,
      "totalscore": 0,
      "asin_de": "B076KT8HT2",
      "price_de": 0,
      "amazon_de": ""
    },
    {
      "name": "5t (64GB)",
      "brand": "OnePlus",
      "imagelink": "images\\/qPbTGxu.jpg",
      "price": 499,
      "design": 5,
      "display": 6,
      "length": 156,
      "width": 75,
      "processor": 5,
      "updates": 4,
      "camera": 4,
      "battery": 4,
      "storage": 64,
      "memory": 6,
      "sdslot": 0,
      "simcards": 2,
      "headphonejack": 1,
      "totalscore": 0,
      "asin_de": "B078WSQ4SC",
      "price_de": 0,
      "amazon_de": ""
    },
    {
      "name": "5t (128GB)",
      "brand": "OnePlus",
      "imagelink": "images\\/qPbTGxu.jpg",
      "price": 559,
      "design": 5,
      "display": 6,
      "length": 156,
      "width": 75,
      "processor": 5,
      "updates": 4,
      "camera": 4,
      "battery": 4,
      "storage": 128,
      "memory": 8,
      "sdslot": 0,
      "simcards": 2,
      "headphonejack": 1,
      "totalscore": 0,
      "asin_de": "B078WSFXPW",
      "price_de": 0,
      "amazon_de": ""
    },
    {
      "name": "Honor 7X",
      "brand": "Huawei",
      "imagelink": "images\\/9chGwId.jpg",
      "price": 236,
      "design": 4,
      "display": 5.9,
      "length": 157,
      "width": 75,
      "processor": 3,
      "updates": 4,
      "camera": 3,
      "battery": 4,
      "storage": 64,
      "memory": 4,
      "sdslot": 1,
      "simcards": 2,
      "headphonejack": 1,
      "totalscore": 0,
      "asin_de": "B0779STLGF",
      "price_de": 0,
      "amazon_de": ""
    },
    {
      "name": "P20",
      "brand": "Huawei",
      "imagelink": "images\\/vqPQcia.jpg",
      "price": 539,
      "design": 5,
      "display": 5.8,
      "length": 149,
      "width": 71,
      "processor": 4,
      "updates": 4,
      "camera": 5,
      "battery": 4,
      "storage": 128,
      "memory": 4,
      "sdslot": 0,
      "simcards": 2,
      "headphonejack": 0,
      "totalscore": 0,
      "asin_de": "B07BHD7MHL",
      "price_de": 0,
      "amazon_de": ""
    },
    {
      "name": "P20 lite",
      "brand": "Huawei",
      "imagelink": "images\\/5wTSOmp.jpg",
      "price": 318,
      "design": 4,
      "display": 5.8,
      "length": 149,
      "width": 71,
      "processor": 4,
      "updates": 4,
      "camera": 3,
      "battery": 4,
      "storage": 64,
      "memory": 4,
      "sdslot": 1,
      "simcards": 2,
      "headphonejack": 1,
      "totalscore": 0,
      "asin_de": "B07BHDC9V6",
      "price_de": 0,
      "amazon_de": ""
    },
    {
      "name": "P20 Pro",
      "brand": "Huawei",
      "imagelink": "images\\/Vc0thgM.jpg",
      "price": 787,
      "design": 5,
      "display": 6.1,
      "length": 155,
      "width": 74,
      "processor": 5,
      "updates": 4,
      "camera": 5,
      "battery": 5,
      "storage": 128,
      "memory": 6,
      "sdslot": 1,
      "simcards": 2,
      "headphonejack": 1,
      "totalscore": 0,
      "asin_de": "B07BHDMHR1",
      "price_de": 0,
      "amazon_de": ""
    },
    {
      "name": "Phone",
      "brand": "Essential",
      "imagelink": "images\\/OGr1dfB.jpg",
      "price": 560,
      "design": 5,
      "display": 5.7,
      "length": 142,
      "width": 71,
      "processor": 5,
      "updates": 5,
      "camera": 5,
      "battery": 4,
      "storage": 128,
      "memory": 4,
      "sdslot": 0,
      "simcards": 1,
      "headphonejack": 0,
      "totalscore": 0,
      "asin_de": "B074BWGRKH",
      "price_de": 0,
      "amazon_de": ""
    },
    {
      "name": "G6",
      "brand": "LG",
      "imagelink": "images\\/814YBWa7gGL._SY879_.jpg",
      "price": 324,
      "design": 3,
      "display": 5.7,
      "length": 149,
      "width": 72,
      "processor": 4,
      "updates": 4,
      "camera": 4,
      "battery": 4,
      "storage": 32,
      "memory": 4,
      "sdslot": 1,
      "simcards": 1,
      "headphonejack": 1,
      "totalscore": 0,
      "asin_de": "B06XFRBM26",
      "price_de": 0,
      "amazon_de": ""
    },
    {
      "name": "V30",
      "brand": "LG",
      "imagelink": "images\\/715GbwmYJjL._SY879_.jpg",
      "price": 512,
      "design": 3,
      "display": 6,
      "length": 152,
      "width": 75,
      "processor": 5,
      "updates": 4,
      "camera": 4,
      "battery": 4,
      "storage": 32,
      "memory": 4,
      "sdslot": 2,
      "simcards": 2,
      "headphonejack": 1,
      "totalscore": 0,
      "asin_de": "B075GYD539",
      "price_de": 0,
      "amazon_de": ""
    },
    {
      "name": "Xperia XZ2",
      "brand": "Sony",
      "imagelink": "images\\/lis9AWg.jpg",
      "price": 623,
      "design": 3,
      "display": 5.7,
      "length": 153,
      "width": 72,
      "processor": 5,
      "updates": 4,
      "camera": 4,
      "battery": 4,
      "storage": 64,
      "memory": 4,
      "sdslot": 1,
      "simcards": 2,
      "headphonejack": 0,
      "totalscore": 0,
      "asin_de": "B079YSBTY7",
      "price_de": 0,
      "amazon_de": ""
    },
    {
      "name": "Xperia XZ2 Compact",
      "brand": "Sony",
      "imagelink": "images\\/ExuzR25.jpg",
      "price": 585,
      "design": 3,
      "display": 5,
      "length": 135,
      "width": 65,
      "processor": 5,
      "updates": 4,
      "camera": 4,
      "battery": 3,
      "storage": 64,
      "memory": 4,
      "sdslot": 1,
      "simcards": 2,
      "headphonejack": 0,
      "totalscore": 0,
      "asin_de": "B079YZ7ZS4",
      "price_de": 0,
      "amazon_de": ""
    },
    {
      "name": "iPhone 8 (64GB)",
      "brand": "Apple",
      "imagelink": "images\\/xGEFWor.jpg",
      "price": 665,
      "design": 3,
      "display": 4.7,
      "length": 138,
      "width": 67,
      "processor": 5,
      "updates": 5,
      "camera": 5,
      "battery": 4,
      "storage": 64,
      "memory": 2,
      "sdslot": 0,
      "simcards": 1,
      "headphonejack": 0,
      "totalscore": 0,
      "asin_de": "B075LXNGFH",
      "price_de": 0,
      "amazon_de": ""
    },
    {
      "name": "iPhone 8 (256GB)",
      "brand": "Apple",
      "imagelink": "images\\/xGEFWor.jpg",
      "price": 760,
      "design": 3,
      "display": 4.7,
      "length": 138,
      "width": 67,
      "processor": 5,
      "updates": 5,
      "camera": 5,
      "battery": 4,
      "storage": 256,
      "memory": 2,
      "sdslot": 0,
      "simcards": 1,
      "headphonejack": 0,
      "totalscore": 0,
      "asin_de": "B075LX5T7P",
      "price_de": 0,
      "amazon_de": ""
    },
    {
      "name": "iPhone 8 Plus (64GB)",
      "brand": "Apple",
      "imagelink": "images\\/lq2EmJG.jpg",
      "price": 783,
      "design": 3,
      "display": 5.5,
      "length": 158,
      "width": 78,
      "processor": 5,
      "updates": 5,
      "camera": 5,
      "battery": 4,
      "storage": 64,
      "memory": 3,
      "sdslot": 0,
      "simcards": 1,
      "headphonejack": 0,
      "totalscore": 0,
      "asin_de": "B075LZ4VQW",
      "price_de": 0,
      "amazon_de": ""
    },
    {
      "name": "iPhone 8 Plus (256GB)",
      "brand": "Apple",
      "imagelink": "images\\/lq2EmJG.jpg",
      "price": 926,
      "design": 3,
      "display": 5.5,
      "length": 158,
      "width": 78,
      "processor": 5,
      "updates": 5,
      "camera": 5,
      "battery": 4,
      "storage": 256,
      "memory": 3,
      "sdslot": 0,
      "simcards": 1,
      "headphonejack": 0,
      "totalscore": 0,
      "asin_de": "B075LY524V",
      "price_de": 0,
      "amazon_de": ""
    },
    {
      "name": "iPhone X (64GB)",
      "brand": "Apple",
      "imagelink": "images\\/UDV8YUp.jpg",
      "price": 995,
      "design": 5,
      "display": 5.8,
      "length": 144,
      "width": 77,
      "processor": 5,
      "updates": 5,
      "camera": 5,
      "battery": 4,
      "storage": 64,
      "memory": 3,
      "sdslot": 0,
      "simcards": 1,
      "headphonejack": 0,
      "totalscore": 0,
      "asin_de": "B075LXNK24",
      "price_de": 0,
      "amazon_de": ""
    },
    {
      "name": "iPhone X (256GB)",
      "brand": "Apple",
      "imagelink": "images\\/UDV8YUp.jpg",
      "price": 1150,
      "design": 5,
      "display": 5.8,
      "length": 144,
      "width": 77,
      "processor": 5,
      "updates": 5,
      "camera": 5,
      "battery": 4,
      "storage": 256,
      "memory": 3,
      "sdslot": 0,
      "simcards": 1,
      "headphonejack": 0,
      "totalscore": 0,
      "asin_de": "B075LWF4C3",
      "price_de": 0,
      "amazon_de": ""
    },
    {
      "name": "Moto X4",
      "brand": "Motorola",
      "imagelink": "images\\/61eEr3fsroL._SY879_.jpg",
      "price": 289,
      "design": 3,
      "display": 5.2,
      "length": 148,
      "width": 73,
      "processor": 3,
      "updates": 5,
      "camera": 4,
      "battery": 5,
      "storage": 32,
      "memory": 3,
      "sdslot": 1,
      "simcards": 2,
      "headphonejack": 1,
      "totalscore": 0,
      "asin_de": "B074MHFGFS",
      "price_de": 0,
      "amazon_de": ""
    },
    {
      "name": "Moto G6",
      "brand": "Motorola",
      "imagelink": "images\\/v3WB6HT.jpg",
      "price": 249,
      "design": 3,
      "display": 5.7,
      "length": 154,
      "width": 72,
      "processor": 3,
      "updates": 3,
      "camera": 3,
      "battery": 3,
      "storage": 32,
      "memory": 3,
      "sdslot": 1,
      "simcards": 2,
      "headphonejack": 1,
      "totalscore": 0,
      "asin_de": "B07BXWZ8ZG",
      "price_de": 0,
      "amazon_de": ""
    },
    {
      "name": "Moto G6 Plus",
      "brand": "Motorola",
      "imagelink": "images\\/phQJx7z.jpg",
      "price": 299,
      "design": 3,
      "display": 5.9,
      "length": 160,
      "width": 76,
      "processor": 3,
      "updates": 3,
      "camera": 4,
      "battery": 3,
      "storage": 64,
      "memory": 3,
      "sdslot": 1,
      "simcards": 2,
      "headphonejack": 1,
      "totalscore": 0,
      "asin_de": "B07CBC869D",
      "price_de": 0,
      "amazon_de": ""
    },
    {
      "name": "Moto G6 Play",
      "brand": "Motorola",
      "imagelink": "images\\/JQ7Vnzc.jpg",
      "price": 199,
      "design": 3,
      "display": 5.7,
      "length": 154,
      "width": 72,
      "processor": 2,
      "updates": 2,
      "camera": 3,
      "battery": 5,
      "storage": 32,
      "memory": 3,
      "sdslot": 1,
      "simcards": 2,
      "headphonejack": 1,
      "totalscore": 0,
      "asin_de": "B07BXFRK2Q",
      "price_de": 0,
      "amazon_de": ""
    },
    {
      "name": "Moto E4",
      "brand": "Motorola",
      "imagelink": "images\\/71r21xr50KL._SY879_.jpg",
      "price": 110,
      "design": 2,
      "display": 5,
      "length": 144,
      "width": 73,
      "processor": 2,
      "updates": 2,
      "camera": 2,
      "battery": 2,
      "storage": 16,
      "memory": 2,
      "sdslot": 1,
      "simcards": 2,
      "headphonejack": 1,
      "totalscore": 0,
      "asin_de": "B073Q2D8RJ",
      "price_de": 0,
      "amazon_de": ""
    },
    {
      "name": "Moto E4 Plus",
      "brand": "Motorola",
      "imagelink": "images\\/motoe4plus.jpg",
      "price": 139,
      "design": 2,
      "display": 5.5,
      "length": 155,
      "width": 78,
      "processor": 2,
      "updates": 2,
      "camera": 2,
      "battery": 4,
      "storage": 16,
      "memory": 3,
      "sdslot": 1,
      "simcards": 2,
      "headphonejack": 1,
      "totalscore": 0,
      "asin_de": "B072C8DPKW",
      "price_de": 0,
      "amazon_de": ""
    },
    {
      "name": "Moto G5S",
      "brand": "Motorola",
      "imagelink": "images\\/S9FO30n.jpg",
      "price": 147,
      "design": 3,
      "display": 5.2,
      "length": 150,
      "width": 74,
      "processor": 3,
      "updates": 2,
      "camera": 3,
      "battery": 3,
      "storage": 32,
      "memory": 3,
      "sdslot": 1,
      "simcards": 2,
      "headphonejack": 1,
      "totalscore": 0,
      "asin_de": "B074MGP8GJ",
      "price_de": 0,
      "amazon_de": ""
    },
    {
      "name": "Moto G5S Plus",
      "brand": "Motorola",
      "imagelink": "images\\/tdlPqFG.jpg",
      "price": 200,
      "design": 3,
      "display": 5.5,
      "length": 154,
      "width": 76,
      "processor": 3,
      "updates": 2,
      "camera": 3,
      "battery": 3,
      "storage": 32,
      "memory": 3,
      "sdslot": 1,
      "simcards": 2,
      "headphonejack": 1,
      "totalscore": 0,
      "asin_de": "B074SR2DVT",
      "price_de": 0,
      "amazon_de": ""
    },
    {
      "name": "Galaxy A5",
      "brand": "Samsung",
      "imagelink": "images\\/wrIcHyN.jpg",
      "price": 236,
      "design": 1,
      "display": 5.2,
      "length": 146,
      "width": 71,
      "processor": 3,
      "updates": 3,
      "camera": 3,
      "battery": 3,
      "storage": 32,
      "memory": 3,
      "sdslot": 1,
      "simcards": 1,
      "headphonejack": 1,
      "totalscore": 0,
      "asin_de": "B01N6M3K34",
      "price_de": 0,
      "amazon_de": ""
    },
    {
      "name": "Galaxy S9",
      "brand": "Samsung",
      "imagelink": "images\\/71uI%2BnAzruL._SY879_.jpg",
      "price": 629,
      "design": 5,
      "display": 5.8,
      "length": 148,
      "width": 68,
      "processor": 5,
      "updates": 4,
      "camera": 5,
      "battery": 4,
      "storage": 64,
      "memory": 4,
      "sdslot": 1,
      "simcards": 2,
      "headphonejack": 1,
      "totalscore": 0,
      "asin_de": "B079SQ5VHX",
      "price_de": 0,
      "amazon_de": ""
    },
    {
      "name": "Galaxy S9 \\+",
      "brand": "Samsung",
      "imagelink": "images\\/71dd-elhT7L._SY879_.jpg",
      "price": 769,
      "design": 5,
      "display": 6.2,
      "length": 158,
      "width": 74,
      "processor": 5,
      "updates": 4,
      "camera": 5,
      "battery": 4,
      "storage": 64,
      "memory": 6,
      "sdslot": 1,
      "simcards": 2,
      "headphonejack": 1,
      "totalscore": 0,
      "asin_de": "B079SNGV9P",
      "price_de": 0,
      "amazon_de": ""
    },
    {
      "name": "Galaxy S8 Note",
      "brand": "Samsung",
      "imagelink": "images\\/PQYBIud.jpg",
      "price": 643,
      "design": 5,
      "display": 6.3,
      "length": 163,
      "width": 75,
      "processor": 5,
      "updates": 4,
      "camera": 5,
      "battery": 4,
      "storage": 64,
      "memory": 6,
      "sdslot": 1,
      "simcards": 2,
      "headphonejack": 1,
      "totalscore": 0,
      "asin_de": "B074PBH2P4",
      "price_de": 0,
      "amazon_de": ""
    },
    {
      "name": "Galaxy S8",
      "brand": "Samsung",
      "imagelink": "images\\/6gY3U53.jpg",
      "price": 476,
      "design": 5,
      "display": 5.8,
      "length": 148,
      "width": 68,
      "processor": 5,
      "updates": 3,
      "camera": 4,
      "battery": 4,
      "storage": 64,
      "memory": 4,
      "sdslot": 1,
      "simcards": 1,
      "headphonejack": 1,
      "totalscore": 0,
      "asin_de": "B06XJ49G5B",
      "price_de": 0,
      "amazon_de": ""
    }
  ]
}
